### ISSUE TITLE
libMLIRTransforms.so.13git: cannot open shared object file

### ISSUE THREAD

**Issue by drom** [circt/images#2]
The nightly image is broken.

```
firtool --version
firtool: error while loading shared libraries: libMLIRTransforms.so.13git: cannot open shared object file: No such file or directory
```

https://github.com/circt/perf/runs/1972527049?check_suite_focus=true

**Comment by drom** [comment]
great! do we have a new docker image?

**Comment by seldridge** [comment]
Yeah, docker image is up now. I poked the `circt/perf` manual workflow and it seemed to run through a-okay.

**Comment by drom** [comment]
Great! Thank you for the fix!
